//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient_GlobalTextAnalyzer.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://example/", ConfigurationName="ServiceReference1.HelloWorld")]
    public interface HelloWorld {
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://example/HelloWorld/makeCapsRequest", ReplyAction="http://example/HelloWorld/makeCapsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebClient_GlobalTextAnalyzer.ServiceReference1.makeCapsResponse makeCaps(WebClient_GlobalTextAnalyzer.ServiceReference1.makeCapsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://example/HelloWorld/makeCapsRequest", ReplyAction="http://example/HelloWorld/makeCapsResponse")]
        System.Threading.Tasks.Task<WebClient_GlobalTextAnalyzer.ServiceReference1.makeCapsResponse> makeCapsAsync(WebClient_GlobalTextAnalyzer.ServiceReference1.makeCapsRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://example/HelloWorld/countOneWordRequest", ReplyAction="http://example/HelloWorld/countOneWordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebClient_GlobalTextAnalyzer.ServiceReference1.countOneWordResponse countOneWord(WebClient_GlobalTextAnalyzer.ServiceReference1.countOneWordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://example/HelloWorld/countOneWordRequest", ReplyAction="http://example/HelloWorld/countOneWordResponse")]
        System.Threading.Tasks.Task<WebClient_GlobalTextAnalyzer.ServiceReference1.countOneWordResponse> countOneWordAsync(WebClient_GlobalTextAnalyzer.ServiceReference1.countOneWordRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://example/HelloWorld/countWordsRequest", ReplyAction="http://example/HelloWorld/countWordsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebClient_GlobalTextAnalyzer.ServiceReference1.countWordsResponse countWords(WebClient_GlobalTextAnalyzer.ServiceReference1.countWordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://example/HelloWorld/countWordsRequest", ReplyAction="http://example/HelloWorld/countWordsResponse")]
        System.Threading.Tasks.Task<WebClient_GlobalTextAnalyzer.ServiceReference1.countWordsResponse> countWordsAsync(WebClient_GlobalTextAnalyzer.ServiceReference1.countWordsRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://example/HelloWorld/countCharactersRequest", ReplyAction="http://example/HelloWorld/countCharactersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebClient_GlobalTextAnalyzer.ServiceReference1.countCharactersResponse countCharacters(WebClient_GlobalTextAnalyzer.ServiceReference1.countCharactersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://example/HelloWorld/countCharactersRequest", ReplyAction="http://example/HelloWorld/countCharactersResponse")]
        System.Threading.Tasks.Task<WebClient_GlobalTextAnalyzer.ServiceReference1.countCharactersResponse> countCharactersAsync(WebClient_GlobalTextAnalyzer.ServiceReference1.countCharactersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="makeCaps", WrapperNamespace="http://example/", IsWrapped=true)]
    public partial class makeCapsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string text;
        
        public makeCapsRequest() {
        }
        
        public makeCapsRequest(string text) {
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="makeCapsResponse", WrapperNamespace="http://example/", IsWrapped=true)]
    public partial class makeCapsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public makeCapsResponse() {
        }
        
        public makeCapsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countOneWord", WrapperNamespace="http://example/", IsWrapped=true)]
    public partial class countOneWordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string word;
        
        public countOneWordRequest() {
        }
        
        public countOneWordRequest(string text, string word) {
            this.text = text;
            this.word = word;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countOneWordResponse", WrapperNamespace="http://example/", IsWrapped=true)]
    public partial class countOneWordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public countOneWordResponse() {
        }
        
        public countOneWordResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://example/")]
    public partial class pair : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string xField;
        
        private int yField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
                this.RaisePropertyChanged("x");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
                this.RaisePropertyChanged("y");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countWords", WrapperNamespace="http://example/", IsWrapped=true)]
    public partial class countWordsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string text;
        
        public countWordsRequest() {
        }
        
        public countWordsRequest(string text) {
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countWordsResponse", WrapperNamespace="http://example/", IsWrapped=true)]
    public partial class countWordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public WebClient_GlobalTextAnalyzer.ServiceReference1.pair[] @return;
        
        public countWordsResponse() {
        }
        
        public countWordsResponse(WebClient_GlobalTextAnalyzer.ServiceReference1.pair[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countCharacters", WrapperNamespace="http://example/", IsWrapped=true)]
    public partial class countCharactersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string text;
        
        public countCharactersRequest() {
        }
        
        public countCharactersRequest(string text) {
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countCharactersResponse", WrapperNamespace="http://example/", IsWrapped=true)]
    public partial class countCharactersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public WebClient_GlobalTextAnalyzer.ServiceReference1.pair[] @return;
        
        public countCharactersResponse() {
        }
        
        public countCharactersResponse(WebClient_GlobalTextAnalyzer.ServiceReference1.pair[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloWorldChannel : WebClient_GlobalTextAnalyzer.ServiceReference1.HelloWorld, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldClient : System.ServiceModel.ClientBase<WebClient_GlobalTextAnalyzer.ServiceReference1.HelloWorld>, WebClient_GlobalTextAnalyzer.ServiceReference1.HelloWorld {
        
        public HelloWorldClient() {
        }
        
        public HelloWorldClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloWorldClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient_GlobalTextAnalyzer.ServiceReference1.makeCapsResponse WebClient_GlobalTextAnalyzer.ServiceReference1.HelloWorld.makeCaps(WebClient_GlobalTextAnalyzer.ServiceReference1.makeCapsRequest request) {
            return base.Channel.makeCaps(request);
        }
        
        public string makeCaps(string text) {
            WebClient_GlobalTextAnalyzer.ServiceReference1.makeCapsRequest inValue = new WebClient_GlobalTextAnalyzer.ServiceReference1.makeCapsRequest();
            inValue.text = text;
            WebClient_GlobalTextAnalyzer.ServiceReference1.makeCapsResponse retVal = ((WebClient_GlobalTextAnalyzer.ServiceReference1.HelloWorld)(this)).makeCaps(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient_GlobalTextAnalyzer.ServiceReference1.makeCapsResponse> WebClient_GlobalTextAnalyzer.ServiceReference1.HelloWorld.makeCapsAsync(WebClient_GlobalTextAnalyzer.ServiceReference1.makeCapsRequest request) {
            return base.Channel.makeCapsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient_GlobalTextAnalyzer.ServiceReference1.makeCapsResponse> makeCapsAsync(string text) {
            WebClient_GlobalTextAnalyzer.ServiceReference1.makeCapsRequest inValue = new WebClient_GlobalTextAnalyzer.ServiceReference1.makeCapsRequest();
            inValue.text = text;
            return ((WebClient_GlobalTextAnalyzer.ServiceReference1.HelloWorld)(this)).makeCapsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient_GlobalTextAnalyzer.ServiceReference1.countOneWordResponse WebClient_GlobalTextAnalyzer.ServiceReference1.HelloWorld.countOneWord(WebClient_GlobalTextAnalyzer.ServiceReference1.countOneWordRequest request) {
            return base.Channel.countOneWord(request);
        }
        
        public int countOneWord(string text, string word) {
            WebClient_GlobalTextAnalyzer.ServiceReference1.countOneWordRequest inValue = new WebClient_GlobalTextAnalyzer.ServiceReference1.countOneWordRequest();
            inValue.text = text;
            inValue.word = word;
            WebClient_GlobalTextAnalyzer.ServiceReference1.countOneWordResponse retVal = ((WebClient_GlobalTextAnalyzer.ServiceReference1.HelloWorld)(this)).countOneWord(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient_GlobalTextAnalyzer.ServiceReference1.countOneWordResponse> WebClient_GlobalTextAnalyzer.ServiceReference1.HelloWorld.countOneWordAsync(WebClient_GlobalTextAnalyzer.ServiceReference1.countOneWordRequest request) {
            return base.Channel.countOneWordAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient_GlobalTextAnalyzer.ServiceReference1.countOneWordResponse> countOneWordAsync(string text, string word) {
            WebClient_GlobalTextAnalyzer.ServiceReference1.countOneWordRequest inValue = new WebClient_GlobalTextAnalyzer.ServiceReference1.countOneWordRequest();
            inValue.text = text;
            inValue.word = word;
            return ((WebClient_GlobalTextAnalyzer.ServiceReference1.HelloWorld)(this)).countOneWordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient_GlobalTextAnalyzer.ServiceReference1.countWordsResponse WebClient_GlobalTextAnalyzer.ServiceReference1.HelloWorld.countWords(WebClient_GlobalTextAnalyzer.ServiceReference1.countWordsRequest request) {
            return base.Channel.countWords(request);
        }
        
        public WebClient_GlobalTextAnalyzer.ServiceReference1.pair[] countWords(string text) {
            WebClient_GlobalTextAnalyzer.ServiceReference1.countWordsRequest inValue = new WebClient_GlobalTextAnalyzer.ServiceReference1.countWordsRequest();
            inValue.text = text;
            WebClient_GlobalTextAnalyzer.ServiceReference1.countWordsResponse retVal = ((WebClient_GlobalTextAnalyzer.ServiceReference1.HelloWorld)(this)).countWords(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient_GlobalTextAnalyzer.ServiceReference1.countWordsResponse> WebClient_GlobalTextAnalyzer.ServiceReference1.HelloWorld.countWordsAsync(WebClient_GlobalTextAnalyzer.ServiceReference1.countWordsRequest request) {
            return base.Channel.countWordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient_GlobalTextAnalyzer.ServiceReference1.countWordsResponse> countWordsAsync(string text) {
            WebClient_GlobalTextAnalyzer.ServiceReference1.countWordsRequest inValue = new WebClient_GlobalTextAnalyzer.ServiceReference1.countWordsRequest();
            inValue.text = text;
            return ((WebClient_GlobalTextAnalyzer.ServiceReference1.HelloWorld)(this)).countWordsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient_GlobalTextAnalyzer.ServiceReference1.countCharactersResponse WebClient_GlobalTextAnalyzer.ServiceReference1.HelloWorld.countCharacters(WebClient_GlobalTextAnalyzer.ServiceReference1.countCharactersRequest request) {
            return base.Channel.countCharacters(request);
        }
        
        public WebClient_GlobalTextAnalyzer.ServiceReference1.pair[] countCharacters(string text) {
            WebClient_GlobalTextAnalyzer.ServiceReference1.countCharactersRequest inValue = new WebClient_GlobalTextAnalyzer.ServiceReference1.countCharactersRequest();
            inValue.text = text;
            WebClient_GlobalTextAnalyzer.ServiceReference1.countCharactersResponse retVal = ((WebClient_GlobalTextAnalyzer.ServiceReference1.HelloWorld)(this)).countCharacters(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient_GlobalTextAnalyzer.ServiceReference1.countCharactersResponse> WebClient_GlobalTextAnalyzer.ServiceReference1.HelloWorld.countCharactersAsync(WebClient_GlobalTextAnalyzer.ServiceReference1.countCharactersRequest request) {
            return base.Channel.countCharactersAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient_GlobalTextAnalyzer.ServiceReference1.countCharactersResponse> countCharactersAsync(string text) {
            WebClient_GlobalTextAnalyzer.ServiceReference1.countCharactersRequest inValue = new WebClient_GlobalTextAnalyzer.ServiceReference1.countCharactersRequest();
            inValue.text = text;
            return ((WebClient_GlobalTextAnalyzer.ServiceReference1.HelloWorld)(this)).countCharactersAsync(inValue);
        }
    }
}
